/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CadastrodeplanoController;
import Model.Cadastrodeplano;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ALUNO
 */
public class TelaCadastroDePlano extends javax.swing.JFrame {
    
    CadastrodeplanoController controller = new CadastrodeplanoController(); 
    /**
     * Creates new form cadastroPlano2
     */
    int id;
    public TelaCadastroDePlano() {
        initComponents();
        listarplanotabela();
   
        campoPesquisarPlano.getDocument().addDocumentListener
            ( new javax.swing.event.DocumentListener(){
            
            public void insertUpdate(javax.swing.event.DocumentEvent e ){
                pesquisar();
            }
            public void removeUpdate(javax.swing.event.DocumentEvent e){
                pesquisar();
            }
            public void changedUpdate(javax.swing.event.DocumentEvent e){
                pesquisar();
            }
            public void pesquisar (){
                String textoPesquisar  = campoPesquisarPlano.getText();
                 filtrarPlanos (textoPesquisar);
            }
        });         
                    
       tabelaPlano.addMouseListener(new java.awt.event.MouseAdapter() {

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int linha = tabelaPlano.getSelectedRow();
        if (linha >= 0) {

            // Pegando os dados da linha clicada (coluna por coluna)

            String idPLANOS = tabelaPlano.getValueAt(linha, 5).toString();
            String nomePlano = tabelaPlano.getValueAt(linha, 0).toString();
            String descricaoPlano = tabelaPlano.getValueAt(linha, 1).toString();
            String valorPlano = tabelaPlano.getValueAt(linha, 2).toString();
            String taxaPlano = tabelaPlano.getValueAt(linha, 4).toString();
            String statusPlano = tabelaPlano.getValueAt(linha, 3).toString();
            // Preenchendo os campos de texto
           
            campoPlano.setText(nomePlano);
            descricaoplano.setText(descricaoPlano);
            valorplano.setText(valorPlano);
            taxaplano.setText(taxaPlano);
            campostatus.setSelectedItem(statusPlano);   
            id = Integer.parseInt(idPLANOS);
        }

    }

});   }
    
    
    public void filtrarPlanos (String textoPesquisar){
          List<Cadastrodeplano> listarPlano = controller.buscarPorNome(textoPesquisar);
          DefaultTableModel modelo = (DefaultTableModel)
                 tabelaPlano.getModel();
                 modelo.setRowCount(0);
                 
                 for(Cadastrodeplano pn: listarPlano){
                   modelo.addRow(new Object[]{
                   
                     pn.getNomePlano(),
                     pn.getDescricaoPlano(),
                     pn.getValorPlano(),
                     pn.getStatusPlano(),
                     pn.getTaxaPlano(),
                     pn.getIdPLANOS()
                 });
                 }
                 tabelaPlano.setModel(modelo);
        }      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        taxaadesao = new javax.swing.JLabel();
        cadastrodeplano = new javax.swing.JLabel();
        taxaplano = new javax.swing.JTextField();
        statusplano = new javax.swing.JLabel();
        nomeplano = new javax.swing.JLabel();
        campostatus = new javax.swing.JComboBox<>();
        driscricaodoplano = new javax.swing.JLabel();
        cadastroPlano = new javax.swing.JButton();
        descricaoplano = new javax.swing.JTextField();
        editarPlano = new javax.swing.JButton();
        valormensal = new javax.swing.JLabel();
        valorplano = new javax.swing.JTextField();
        campoPlano = new javax.swing.JTextField();
        voltarMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoPesquisarPlano = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPlano = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        menuPlano = new javax.swing.JMenuBar();
        botaoHome = new javax.swing.JMenu();
        menuinicial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taxaadesao.setBackground(new java.awt.Color(102, 0, 102));
        taxaadesao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        taxaadesao.setForeground(new java.awt.Color(255, 255, 255));
        taxaadesao.setText("TAXA DE ADESÃO: ");
        jPanel1.add(taxaadesao, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        cadastrodeplano.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        cadastrodeplano.setForeground(new java.awt.Color(255, 255, 255));
        cadastrodeplano.setText("CADASTRO DE PLANO");
        jPanel1.add(cadastrodeplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 220, -1));

        taxaplano.setBackground(new java.awt.Color(102, 0, 102));
        taxaplano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        taxaplano.setForeground(new java.awt.Color(255, 255, 255));
        taxaplano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxaplanoActionPerformed(evt);
            }
        });
        jPanel1.add(taxaplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 150, 30));

        statusplano.setBackground(new java.awt.Color(102, 0, 102));
        statusplano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        statusplano.setForeground(new java.awt.Color(255, 255, 255));
        statusplano.setText("STATUS DO PLANO: ");
        jPanel1.add(statusplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, 20));

        nomeplano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nomeplano.setForeground(new java.awt.Color(255, 255, 255));
        nomeplano.setText("NOME DO PLANO:");
        jPanel1.add(nomeplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 140, -1));

        campostatus.setBackground(new java.awt.Color(102, 0, 102));
        campostatus.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campostatus.setForeground(new java.awt.Color(255, 255, 255));
        campostatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Desativado" }));
        campostatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campostatusActionPerformed(evt);
            }
        });
        jPanel1.add(campostatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 170, -1));

        driscricaodoplano.setBackground(new java.awt.Color(102, 0, 102));
        driscricaodoplano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        driscricaodoplano.setForeground(new java.awt.Color(255, 255, 255));
        driscricaodoplano.setText("DESCRIÇÃO DO PLANO: ");
        jPanel1.add(driscricaodoplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        cadastroPlano.setBackground(new java.awt.Color(102, 0, 102));
        cadastroPlano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cadastroPlano.setForeground(new java.awt.Color(255, 255, 255));
        cadastroPlano.setText("CADASTRAR");
        cadastroPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPlanoActionPerformed(evt);
            }
        });
        jPanel1.add(cadastroPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 840, -1, -1));

        descricaoplano.setBackground(new java.awt.Color(102, 0, 102));
        descricaoplano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        descricaoplano.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(descricaoplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 410, 30));

        editarPlano.setBackground(new java.awt.Color(102, 0, 102));
        editarPlano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        editarPlano.setForeground(new java.awt.Color(255, 255, 255));
        editarPlano.setText("EDITAR");
        editarPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPlanoActionPerformed(evt);
            }
        });
        jPanel1.add(editarPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 840, -1, -1));

        valormensal.setBackground(new java.awt.Color(102, 0, 102));
        valormensal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        valormensal.setForeground(new java.awt.Color(255, 255, 255));
        valormensal.setText("VALOR MENSAL:");
        jPanel1.add(valormensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        valorplano.setBackground(new java.awt.Color(102, 0, 102));
        valorplano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        valorplano.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(valorplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 150, 30));

        campoPlano.setBackground(new java.awt.Color(102, 0, 102));
        campoPlano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoPlano.setForeground(new java.awt.Color(255, 255, 255));
        campoPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPlanoActionPerformed(evt);
            }
        });
        jPanel1.add(campoPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 450, 30));

        voltarMenu.setBackground(new java.awt.Color(102, 0, 102));
        voltarMenu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        voltarMenu.setForeground(new java.awt.Color(255, 255, 255));
        voltarMenu.setText("VOLTAR");
        voltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarMenuActionPerformed(evt);
            }
        });
        jPanel1.add(voltarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 930, 100, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PESQUISAR: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 100, 30));

        campoPesquisarPlano.setBackground(new java.awt.Color(102, 0, 102));
        campoPesquisarPlano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoPesquisarPlano.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(campoPesquisarPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 630, 30));

        tabelaPlano.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome do Plano", "Descrição do Plano", "Valor", "Status do Plano", "Adesão", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaPlano);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 750, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\ProjetoBitNexus\\src\\main\\java\\img\\Fundo.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1940, 1080));

        botaoHome.setText("HOME");

        menuinicial.setText("MENU INICIAL");
        menuinicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuinicialActionPerformed(evt);
            }
        });
        botaoHome.add(menuinicial);

        menuPlano.add(botaoHome);

        setJMenuBar(menuPlano);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1915, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPlanoActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_campoPlanoActionPerformed

    private void cadastroPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPlanoActionPerformed
        // TODO add your handling code here:
        Cadastrodeplano plano = new Cadastrodeplano();
         
      plano.setNomePlano((String)campoPlano.getText());
      plano.setDescricaoPlano((String)descricaoplano.getText());
      plano.setValorPlano(Double.parseDouble(valorplano.getText()));
      plano.setTaxaPlano(Double.parseDouble(taxaplano.getText()));
      plano.setStatusPlano((String)campostatus.getSelectedItem());
      
      boolean result = controller.inserir(plano);
      
       /*if(controler.Cadastrodeplano(plano)){
           JOptionPane.showMessageDialog(null,"Cadastro com sucesso");
       } else {   
          JOptionPane.showMessageDialog(null,"Erro ao realizar");
        }*/
        if (result == true){
            JOptionPane.showMessageDialog(null, "Cadastro de plano realizado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar");
        }
        listarplanotabela();
    }//GEN-LAST:event_cadastroPlanoActionPerformed

    public void listarplanotabela(){
           List<Cadastrodeplano> listarplano = controller.listarTodos();
           DefaultTableModel modelo = (DefaultTableModel)
                 tabelaPlano.getModel();
                 modelo.setRowCount(0);
                 
                 for(Cadastrodeplano pn: listarplano){
                   modelo.addRow(new Object[]{
                   
                     pn.getNomePlano(),
                     pn.getDescricaoPlano(),
                     pn.getValorPlano(),
                     pn.getStatusPlano(),
                     pn.getTaxaPlano(),
                     pn.getIdPLANOS()
                 });
                 }
                 tabelaPlano.setModel(modelo);
                    
                    //oculta a coluna do ID
                 tabelaPlano.getColumnModel().getColumn(5).setMinWidth(0);
                 tabelaPlano.getColumnModel().getColumn(5).setMaxWidth(0);
                 tabelaPlano.getColumnModel().getColumn(5).setWidth(0);    
       } 
   
    
    private void campostatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campostatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campostatusActionPerformed

    private void voltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarMenuActionPerformed
        // TODO add your handling code here:
       TelaHome voltarMenu = new TelaHome() ;
        voltarMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarMenuActionPerformed

        private void botaoHomeMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
           TelaHome voltarMenu = new TelaHome() ;
        voltarMenu.setVisible(true);
        dispose();
    }    
    
    private void editarPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPlanoActionPerformed
        // TODO add your handling code here:
        String nomePlano = campoPlano.getText();
        String descricaoPlano = descricaoplano.getText();
        double  valorPlano = Double.parseDouble(valorplano.getText());
        double  taxaPlano = Double.parseDouble(taxaplano.getText());
        String statusPlano= campostatus.getSelectedItem().toString();
          
        Cadastrodeplano plano = new Cadastrodeplano(nomePlano, descricaoPlano, valorPlano, taxaPlano, statusPlano);
        plano.setIdPLANOS(id);
        
                CadastrodeplanoController controller = new CadastrodeplanoController();
                boolean sucesso = controller.atualizar(plano);
                if(sucesso){
                    JOptionPane.showMessageDialog(this, "Plano atualizando com sucesso!");
                listarplanotabela();
                }else{
                        JOptionPane.showMessageDialog(this, "Erro ao autualizar o plano.");
                        }
        
    }//GEN-LAST:event_editarPlanoActionPerformed

    private void menuinicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuinicialActionPerformed
        // TODO add your handling code here:
        TelaHome menuvoltar = new TelaHome();
        menuvoltar.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuinicialActionPerformed

    private void taxaplanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxaplanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxaplanoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDePlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDePlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDePlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDePlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroDePlano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botaoHome;
    private javax.swing.JButton cadastroPlano;
    private javax.swing.JLabel cadastrodeplano;
    private javax.swing.JTextField campoPesquisarPlano;
    private javax.swing.JTextField campoPlano;
    private javax.swing.JComboBox<String> campostatus;
    private javax.swing.JTextField descricaoplano;
    private javax.swing.JLabel driscricaodoplano;
    private javax.swing.JButton editarPlano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuPlano;
    private javax.swing.JMenuItem menuinicial;
    private javax.swing.JLabel nomeplano;
    private javax.swing.JLabel statusplano;
    private javax.swing.JTable tabelaPlano;
    private javax.swing.JLabel taxaadesao;
    private javax.swing.JTextField taxaplano;
    private javax.swing.JLabel valormensal;
    private javax.swing.JTextField valorplano;
    private javax.swing.JButton voltarMenu;
    // End of variables declaration//GEN-END:variables






}
