/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CadastroDeFuncionarioController;
import Controller.ConexaoComBancoDados;
import Model.CadastroDeFuncionarioModel;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 * * @author ALUNO
 */
public class TelaCadastroDeFuncionario extends javax.swing.JFrame {

    CadastroDeFuncionarioController controler = new CadastroDeFuncionarioController();
    int id;
    
    /**
     * Creates new form Casdastrodefuncionario
     */
    public TelaCadastroDeFuncionario() {
        initComponents();
        listarFuncionario();
        
        tabelaFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                
                int linha = tabelaFuncionario.getSelectedRow();
                
                if (linha >= 0){      
                    nomefuncionario.setText(tabelaFuncionario.getValueAt(linha, 0).toString());
                    dataNascimentoFuncionario.setText(tabelaFuncionario.getValueAt(linha, 1).toString());
                    telefone.setText(tabelaFuncionario.getValueAt(linha, 2).toString());
                    cpffuncionario.setText(tabelaFuncionario.getValueAt(linha, 3).toString());
                    emailfuncionario.setText(tabelaFuncionario.getValueAt(linha, 4).toString());
                    senhafuncionario.setText(tabelaFuncionario.getValueAt(linha, 5).toString());
                     id = Integer.parseInt(tabelaFuncionario.getValueAt(linha, 6).toString());         
                }
            }
        
        });
    
          
        campoPesquisaFuncionario.getDocument().addDocumentListener
         (new javax.swing.event.DocumentListener(){
                 
                 public void insertUpdate(javax.swing.event.DocumentEvent  e){
                    pesquisar();
                    }
                 public void removeUpdate(javax.swing.event.DocumentEvent  e){
                    pesquisar();
                    }
                 public void changedUpdate (javax.swing.event.DocumentEvent e){
                    pesquisar();
                    }
                 public void pesquisar(){
                    String textoPesquisaFuncionario = campoPesquisaFuncionario.getText();
                    filtrarFuncionario(textoPesquisaFuncionario);
                    
                    }
                });
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        nomecompleto = new javax.swing.JLabel();
        nomefuncionario = new javax.swing.JTextField();
        cpf = new javax.swing.JLabel();
        cpffuncionario = new javax.swing.JFormattedTextField();
        datadenacimento = new javax.swing.JLabel();
        dataNascimentoFuncionario = new javax.swing.JFormattedTextField();
        email = new javax.swing.JLabel();
        emailfuncionario = new javax.swing.JTextField();
        mostrarsenha = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        senhafuncionario = new javax.swing.JPasswordField();
        cadastrarFuncionario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        fone = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        campoPesquisaFuncionario = new javax.swing.JTextField();
        voltafuncionario = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        menuFuncionario = new javax.swing.JMenuBar();
        botaoHome = new javax.swing.JMenu();
        menuinicial = new javax.swing.JMenuItem();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomecompleto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nomecompleto.setForeground(new java.awt.Color(255, 255, 255));
        nomecompleto.setText("NOME COMPLETO:");
        jPanel1.add(nomecompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 160, 24));

        nomefuncionario.setBackground(new java.awt.Color(102, 0, 102));
        nomefuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nomefuncionario.setForeground(new java.awt.Color(255, 255, 255));
        nomefuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomefuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(nomefuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 460, 30));

        cpf.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cpf.setForeground(new java.awt.Color(255, 255, 255));
        cpf.setText("CPF:");
        jPanel1.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, -1));

        cpffuncionario.setBackground(new java.awt.Color(102, 0, 102));
        cpffuncionario.setForeground(new java.awt.Color(255, 255, 255));
        try {
            cpffuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpffuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cpffuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpffuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(cpffuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 270, 30));

        datadenacimento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        datadenacimento.setForeground(new java.awt.Color(255, 255, 255));
        datadenacimento.setText("DATA DE NASCIMENTO: ");
        jPanel1.add(datadenacimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 190, -1));

        dataNascimentoFuncionario.setBackground(new java.awt.Color(102, 0, 102));
        dataNascimentoFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        try {
            dataNascimentoFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNascimentoFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dataNascimentoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(dataNascimentoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 150, 30));

        email.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("E-MAIL:");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 60, -1));

        emailfuncionario.setBackground(new java.awt.Color(102, 0, 102));
        emailfuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emailfuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(emailfuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 480, 30));

        mostrarsenha.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\ProjetoBitNexus\\src\\main\\java\\img\\hidden.png")); // NOI18N
        mostrarsenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarsenhaMouseClicked(evt);
            }
        });
        jPanel1.add(mostrarsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 240, 30, 30));

        senha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        senha.setForeground(new java.awt.Color(255, 255, 255));
        senha.setText("SENHA:");
        jPanel1.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 70, -1));

        senhafuncionario.setBackground(new java.awt.Color(102, 0, 102));
        senhafuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        senhafuncionario.setForeground(new java.awt.Color(255, 255, 255));
        senhafuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhafuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(senhafuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 480, 30));

        cadastrarFuncionario.setBackground(new java.awt.Color(102, 0, 102));
        cadastrarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cadastrarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarFuncionario.setText("CADASTRAR");
        cadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 690, 130, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRO DE FUNCIONARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 290, 47));

        editar.setBackground(new java.awt.Color(102, 0, 102));
        editar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        editar.setForeground(new java.awt.Color(255, 255, 255));
        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        jPanel1.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 690, -1, -1));

        fone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        fone.setForeground(new java.awt.Color(255, 255, 255));
        fone.setText("TELEFONE:");
        jPanel1.add(fone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 90, -1));

        telefone.setBackground(new java.awt.Color(102, 0, 102));
        telefone.setForeground(new java.awt.Color(255, 255, 255));
        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });
        jPanel1.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 190, 30));

        campoPesquisaFuncionario.setBackground(new java.awt.Color(102, 0, 102));
        campoPesquisaFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        campoPesquisaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesquisaFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(campoPesquisaFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 470, 40));

        voltafuncionario.setBackground(new java.awt.Color(102, 0, 102));
        voltafuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        voltafuncionario.setForeground(new java.awt.Color(255, 255, 255));
        voltafuncionario.setText("VOLTAR");
        voltafuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltafuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(voltafuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 920, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PESQUISAR:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 110, 30));

        tabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome do Funcionário", "Data de Nascimento", "Telefone", "CPF", "Email", "Senha", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaFuncionario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 940, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\ProjetoBitNexus\\src\\main\\java\\img\\Fundo.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1920, 1140));

        botaoHome.setText("HOME");

        menuinicial.setText("MENU INICIAL");
        menuinicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuinicialActionPerformed(evt);
            }
        });
        botaoHome.add(menuinicial);

        menuFuncionario.add(botaoHome);

        setJMenuBar(menuFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1084, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomefuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomefuncionarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nomefuncionarioActionPerformed

    public void listarFuncionario() {
        List<CadastroDeFuncionarioModel> listaFuncionario = controler.listar();
        DefaultTableModel modelo = (DefaultTableModel) tabelaFuncionario.getModel();
        modelo.setRowCount(0);

        for (CadastroDeFuncionarioModel cdfm : listaFuncionario) {
            modelo.addRow(new Object[]{
                cdfm.getNomeFuncionario(),
                cdfm.getDatanascimentoFuncionario(),
                cdfm.getTelefoneFuncionario(),
                cdfm.getCpfFuncionario(),
                cdfm.getEmailFuncionario(),
                cdfm.getSenhaFuncionario(),
                cdfm.getIdFUNCIONARIOS()
            });
        }
        tabelaFuncionario.setModel(modelo);
      
        // oltutar a coluna do ID 
        tabelaFuncionario.getColumnModel().getColumn(6).setMinWidth(0);
        tabelaFuncionario.getColumnModel().getColumn(6).setMaxWidth(0);
        tabelaFuncionario.getColumnModel().getColumn(6).setWidth(0);    
               
    }
   
    
      
    public void limparCampos() {
        nomefuncionario.setText("");
        dataNascimentoFuncionario.setText("");
        telefone.setText("");
        cpffuncionario.setText("");
        emailfuncionario.setText("");
        senhafuncionario.setText("");
        
    }
   
    public void filtrarFuncionario(String textoPesquisaFuncionario){
        List<CadastroDeFuncionarioModel> listaFuncionario = controler.pesquisar(textoPesquisaFuncionario);
        DefaultTableModel modelo = (DefaultTableModel) tabelaFuncionario.getModel();
        modelo.setRowCount(0);
        
            for (CadastroDeFuncionarioModel c : listaFuncionario){
                if (c.getNomeFuncionario().toLowerCase().contains(textoPesquisaFuncionario.toLowerCase()) ||
                    c.getCpfFuncionario().toLowerCase().contains(textoPesquisaFuncionario.toLowerCase())) {
                        
                        modelo.addRow(new Object[]{
                            c.getNomeFuncionario(),
                            c.getDatanascimentoFuncionario(),
                            c.getTelefoneFuncionario(),
                            c.getCpfFuncionario(),
                            c.getEmailFuncionario(),
                            c.getSenhaFuncionario(),
                            c.getIdFUNCIONARIOS()
                          
                        });
                           }
            }
    tabelaFuncionario.setModel(modelo);        
    }
   
    
    
    
    private void cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioActionPerformed
        // TODO add your handling code here   
   
       CadastroDeFuncionarioModel funcionario = new CadastroDeFuncionarioModel();
        // cadastrar os dentro da classe CadastroDeFuncionarioModel
        // getText() funciona apenas para compos do tipo TextField
        funcionario.setNomeFuncionario((String) nomefuncionario.getText());
        funcionario.setDatanascimentoFuncionario((String) dataNascimentoFuncionario.getText());
        funcionario.setTelefoneFuncionario((String) telefone.getText());
        funcionario.setCpfFuncionario((String) cpffuncionario.getText());
        funcionario.setEmailFuncionario((String) emailfuncionario.getText());
        funcionario.setSenhaFuncionario(new String(senhafuncionario.getPassword()));

       boolean result = controler.CadastroDeFuncionario(funcionario);
              
        if (result) {
            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!");
            listarFuncionario();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao realizar cadastro!");
            return;
        }
        /*if (result != false){
            JOptionPane.showMessageDialog(null, "Cadastro de funcionario realizado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar");
        }*/
    }//GEN-LAST:event_cadastrarFuncionarioActionPerformed

    private void dataNascimentoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoFuncionarioActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    private void cpffuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpffuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpffuncionarioActionPerformed

    private void voltafuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltafuncionarioActionPerformed
        // TODO add your handling code here:
        TelaHome voltarMenu = new TelaHome() ;
        voltarMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltafuncionarioActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        CadastroDeFuncionarioModel funcionario = new CadastroDeFuncionarioModel();
        // cadastrar os dentro da classe CadastroDeFuncionarioModel
        // getText() funciona apenas para compos do tipo TextField
        funcionario.setNomeFuncionario((String) nomefuncionario.getText());
        funcionario.setDatanascimentoFuncionario((String) dataNascimentoFuncionario.getText());
        funcionario.setTelefoneFuncionario((String) telefone.getText());
        funcionario.setCpfFuncionario((String) cpffuncionario.getText());
        funcionario.setEmailFuncionario((String) emailfuncionario.getText());
        funcionario.setSenhaFuncionario(new String(senhafuncionario.getPassword()));
        funcionario.setIdFUNCIONARIOS(id);
       
        
        
        if (controler.editarCadastroDeFuncionario(funcionario)) {
            JOptionPane.showMessageDialog(null, "Editado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao realizar editado!");
        }   
          listarFuncionario();
    }//GEN-LAST:event_editarActionPerformed

    private void campoPesquisaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesquisaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesquisaFuncionarioActionPerformed

    private void menuinicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuinicialActionPerformed
        // TODO add your handling code here:
        TelaHome menuvoltar = new TelaHome();
        menuvoltar.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuinicialActionPerformed

    boolean senhavisivel=false;
    private void mostrarsenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarsenhaMouseClicked
        // TODO add your handling code here:
        senhafuncionario.setEchoChar((char)0);
        
        if(senhavisivel == false) {
            senhafuncionario.setEchoChar((char)0);
            senhavisivel=true;
        } else {
            senhafuncionario.setEchoChar('*');
            senhavisivel=false;
        }
    }//GEN-LAST:event_mostrarsenhaMouseClicked

    private void senhafuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhafuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhafuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroDeFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botaoHome;
    private javax.swing.JButton cadastrarFuncionario;
    private javax.swing.JTextField campoPesquisaFuncionario;
    private javax.swing.JLabel cpf;
    private javax.swing.JFormattedTextField cpffuncionario;
    private javax.swing.JFormattedTextField dataNascimentoFuncionario;
    private javax.swing.JLabel datadenacimento;
    private javax.swing.JButton editar;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfuncionario;
    private javax.swing.JLabel fone;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuBar menuFuncionario;
    private javax.swing.JMenuItem menuinicial;
    private javax.swing.JLabel mostrarsenha;
    private javax.swing.JLabel nomecompleto;
    private javax.swing.JTextField nomefuncionario;
    private javax.swing.JLabel senha;
    private javax.swing.JPasswordField senhafuncionario;
    private javax.swing.JTable tabelaFuncionario;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JToggleButton voltafuncionario;
    // End of variables declaration//GEN-END:variables
}
