/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MonitoramentoController;
import Model.MonitoramentoModel;
import View.TelaMonitoramento;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALUNO
 */
public class TelaNovoAparelho extends javax.swing.JFrame {
    
    MonitoramentoController controler = new MonitoramentoController();

    /**
     * Creates new form TelaNovoAparelho
     */
    
     int id;
    public TelaNovoAparelho() {
        initComponents();
        listarDadosMaquinas();
        
        tipoaparelhoPesquisar.addActionListener((tipoaparelho) -> {
            String comboboxPesquisar =  tipoaparelhoPesquisar.getSelectedItem().toString();
            filtrarMaquinas(comboboxPesquisar);
        });
        
        tabelaMonitoramento.addMouseListener(new java.awt.event.MouseAdapter() {
         
         public void mouseClicked(java.awt.event.MouseEvent evt) {

            int linha = tabelaMonitoramento.getSelectedRow();

            if (linha >= 0) {
            id = Integer.parseInt(tabelaMonitoramento.getValueAt(linha, 0).toString()); // pega o ID
            String tipoMaquina = tabelaMonitoramento.getValueAt(linha, 1).toString();
            String nomeMaquina = tabelaMonitoramento.getValueAt(linha, 2).toString();

            tipoaparelho.setSelectedItem(tipoMaquina);
            nomeaparelho.setText(nomeMaquina);
            }
         }
        });
     }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        voltarnovoaparelho = new javax.swing.JButton();
        confirmaraparelho = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tipoaparelhoPesquisar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        nomeaparelho = new javax.swing.JTextField();
        editarAparelho = new javax.swing.JButton();
        pesquisar = new javax.swing.JLabel();
        tipoaparelho = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMonitoramento = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOVO APARELHO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, -1, 40));

        voltarnovoaparelho.setBackground(new java.awt.Color(102, 0, 102));
        voltarnovoaparelho.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        voltarnovoaparelho.setForeground(new java.awt.Color(255, 255, 255));
        voltarnovoaparelho.setText("VOLTAR");
        voltarnovoaparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarnovoaparelhoActionPerformed(evt);
            }
        });
        jPanel1.add(voltarnovoaparelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 920, 100, -1));

        confirmaraparelho.setBackground(new java.awt.Color(102, 0, 102));
        confirmaraparelho.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        confirmaraparelho.setForeground(new java.awt.Color(255, 255, 255));
        confirmaraparelho.setText("CADASTRAR");
        confirmaraparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaraparelhoActionPerformed(evt);
            }
        });
        jPanel1.add(confirmaraparelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 710, 130, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TIPO DE APARELHO: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        tipoaparelhoPesquisar.setBackground(new java.awt.Color(102, 0, 102));
        tipoaparelhoPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tipoaparelhoPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        tipoaparelhoPesquisar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIDEO GAME", "COMPUTADOR", "SIMULADOR" }));
        jPanel1.add(tipoaparelhoPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 290, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOME DO APARELHO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        nomeaparelho.setBackground(new java.awt.Color(102, 0, 102));
        nomeaparelho.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nomeaparelho.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(nomeaparelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 280, -1));

        editarAparelho.setBackground(new java.awt.Color(102, 0, 102));
        editarAparelho.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        editarAparelho.setForeground(new java.awt.Color(255, 255, 255));
        editarAparelho.setText("EDITAR");
        editarAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarAparelhoActionPerformed(evt);
            }
        });
        jPanel1.add(editarAparelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 710, 110, -1));

        pesquisar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        pesquisar.setForeground(new java.awt.Color(255, 255, 255));
        pesquisar.setText("PESQUISAR APARELHO:");
        jPanel1.add(pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 190, 20));

        tipoaparelho.setBackground(new java.awt.Color(102, 0, 102));
        tipoaparelho.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tipoaparelho.setForeground(new java.awt.Color(255, 255, 255));
        tipoaparelho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIDEO GAME", "COMPUTADOR", "SIMULADOR" }));
        jPanel1.add(tipoaparelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 280, -1));

        tabelaMonitoramento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tipo de Aparelho", "Nome do Aparelho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaMonitoramento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 490, 190));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\ProjetoBitNexus\\src\\main\\java\\img\\Fundo.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    public void filtrarMaquinas(String comboboxPesquisar){
        List<MonitoramentoModel> listarMaquina = controler.pesquisar(comboboxPesquisar);
        DefaultTableModel modelo = (DefaultTableModel)tabelaMonitoramento.getModel();
        modelo.setRowCount(0);
        
        for(MonitoramentoModel m: listarMaquina){
            modelo.addRow(new Object[]{
            m.getIdMAQUINAS(),
            m.getNomeMaquina(),
            m.getTipoMaquina()    
            });
        }
        tabelaMonitoramento.setModel(modelo);
    }
   
   public void listarDadosMaquinas() {
    List<MonitoramentoModel> aparelhos = controler.listarMaquinas();
    DefaultTableModel modelo = (DefaultTableModel) tabelaMonitoramento.getModel();
   modelo.setRowCount(0);
    
    for (MonitoramentoModel m : aparelhos) {
        modelo.addRow(new Object[]{
            m.getIdMAQUINAS(),
            m.getTipoMaquina(),
            m.getNomeMaquina()
        });
    }

    tabelaMonitoramento.setModel(modelo);
    
    // Oculta a coluna do ID
    tabelaMonitoramento.getColumnModel().getColumn(0).setMinWidth(0);
    tabelaMonitoramento.getColumnModel().getColumn(0).setMaxWidth(0);
    tabelaMonitoramento.getColumnModel().getColumn(0).setWidth(0);
} 
    
    private void confirmaraparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaraparelhoActionPerformed
        // TODO add your handling code here:
        MonitoramentoModel novoAparelho = new MonitoramentoModel();
        
        novoAparelho.setTipoMaquina(tipoaparelho.getSelectedItem().toString());
        novoAparelho.setNomeMaquina(nomeaparelho.getText()); 
     
        boolean result = controler.Cadastrar(novoAparelho);
        
        if (result == true){
            JOptionPane.showMessageDialog(null, "Cadastro de aparelho realizado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar");
        }
        listarDadosMaquinas();
        limparCampos();
    }//GEN-LAST:event_confirmaraparelhoActionPerformed

    private void voltarnovoaparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarnovoaparelhoActionPerformed
        // TODO add your handling code here:
        TelaHome voltarMenu = new TelaHome() ;
        voltarMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarnovoaparelhoActionPerformed

    private void editarAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarAparelhoActionPerformed
        // TODO add your handling code here:
         String nomeMaquina = nomeaparelho.getText();
         String tipoMaquina = tipoaparelho.getSelectedItem().toString();
         
         MonitoramentoModel novoAparelho = new MonitoramentoModel(nomeMaquina, tipoMaquina);
         novoAparelho.setIdMAQUINAS(id);
         //novoAparelho.setNomeMaquina(nomeMaquina);
         //novoAparelho.setTipoMaquina(tipoMaquina);
         
         boolean sucesso = controler.EditarMaquinas(novoAparelho);
         
         if (sucesso) {
             JOptionPane.showMessageDialog(this,"Aparelho atualizado com sucesso!");
             listarDadosMaquinas();
         } else {
             JOptionPane.showMessageDialog(this,"Erro ao atualizar aparelho.");
         }
    }//GEN-LAST:event_editarAparelhoActionPerformed

    private void limparCampos(){
        nomeaparelho.setText("");
        tipoaparelho.setSelectedItem(0);
        id=0;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovoAparelho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmaraparelho;
    private javax.swing.JButton editarAparelho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeaparelho;
    private javax.swing.JLabel pesquisar;
    private javax.swing.JTable tabelaMonitoramento;
    private javax.swing.JComboBox<String> tipoaparelho;
    private javax.swing.JComboBox<String> tipoaparelhoPesquisar;
    private javax.swing.JButton voltarnovoaparelho;
    // End of variables declaration//GEN-END:variables
}