/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CadastroDeFuncionarioController;
import Model.CadastroDeFuncionarioModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ALUNO
 */
public class TelaLogin extends javax.swing.JFrame {

    //CadastroDeFuncionarioController funcionarioController= new CadastroDeFuncionarioController();
    //CadastroDeFuncionarioModel funcionariologin = new CadastroDeFuncionarioModel();
    
    /**
     * Creates new form LoginView
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel1 = new javax.swing.JPanel();
        campoCpf = new javax.swing.JLabel();
        mostrarsenha = new javax.swing.JLabel();
        varivelSenha = new javax.swing.JLabel();
        butomLogin = new javax.swing.JButton();
        campocpflogin = new javax.swing.JFormattedTextField();
        camposenhalogin = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoCpf.setBackground(new java.awt.Color(255, 255, 255));
        campoCpf.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoCpf.setForeground(new java.awt.Color(255, 255, 255));
        campoCpf.setText("CPF:");
        painel1.add(campoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 50, 20));

        mostrarsenha.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\ProjetoBitNexus\\src\\main\\java\\img\\hidden.png")); // NOI18N
        mostrarsenha.setToolTipText("");
        mostrarsenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarsenhaMouseClicked(evt);
            }
        });
        painel1.add(mostrarsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, 30));

        varivelSenha.setBackground(new java.awt.Color(255, 255, 255));
        varivelSenha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        varivelSenha.setForeground(new java.awt.Color(255, 255, 255));
        varivelSenha.setText("SENHA:");
        painel1.add(varivelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 60, 40));

        butomLogin.setBackground(new java.awt.Color(102, 0, 102));
        butomLogin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        butomLogin.setForeground(new java.awt.Color(255, 255, 255));
        butomLogin.setText("LOGIN");
        butomLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butomLoginMouseClicked(evt);
            }
        });
        butomLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butomLoginActionPerformed(evt);
            }
        });
        painel1.add(butomLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        campocpflogin.setBackground(new java.awt.Color(102, 0, 102));
        campocpflogin.setForeground(new java.awt.Color(255, 255, 255));
        try {
            campocpflogin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campocpflogin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        painel1.add(campocpflogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 280, 30));

        camposenhalogin.setBackground(new java.awt.Color(102, 0, 102));
        camposenhalogin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        camposenhalogin.setForeground(new java.awt.Color(255, 255, 255));
        camposenhalogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camposenhaloginActionPerformed(evt);
            }
        });
        painel1.add(camposenhalogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\ProjetoBitNexus\\src\\main\\java\\img\\Cadastro (2) (2).png")); // NOI18N
        painel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 650));

        getContentPane().add(painel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butomLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butomLoginActionPerformed
        // TODO add your handling code here:
          String cpfFuncionario = campocpflogin.getText().toString();
          String senhaFuncionario = new String (camposenhalogin.getPassword());
       
          CadastroDeFuncionarioController controller = new CadastroDeFuncionarioController();
          CadastroDeFuncionarioModel funcionariologin = controller.realizarLogin(cpfFuncionario, senhaFuncionario);
          
         
       if (funcionariologin  != null){
           JOptionPane.showMessageDialog(this,"Bem Vindo!");
           TelaHome home = new TelaHome();
           home.setVisible(true);
           dispose();
}else{
           JOptionPane.showMessageDialog(this, "Usuário não encontrado!");
       }
    }//GEN-LAST:event_butomLoginActionPerformed

    private void butomLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butomLoginMouseClicked
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_butomLoginMouseClicked

    private void camposenhaloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camposenhaloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camposenhaloginActionPerformed

    boolean senhavisivel = false;
    private void mostrarsenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarsenhaMouseClicked
        // TODO add your handling code here:
        camposenhalogin.setEchoChar((char)0);
        
        if(senhavisivel == false) {
            camposenhalogin.setEchoChar((char)0);
            senhavisivel=true;
        } else {
            camposenhalogin.setEchoChar('*');
            senhavisivel=false;
        }
    }//GEN-LAST:event_mostrarsenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butomLogin;
    private javax.swing.JLabel campoCpf;
    private javax.swing.JFormattedTextField campocpflogin;
    private javax.swing.JPasswordField camposenhalogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mostrarsenha;
    private javax.swing.JPanel painel1;
    private javax.swing.JLabel varivelSenha;
    // End of variables declaration//GEN-END:variables
}
